# Generated by Django 2.2.2 on 2019-09-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190801_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Clients'),
        ),
    ]
